import React from "react";
import "./globals.css";
import { Navbar } from "../components/layout/navbar"; // Adjust the path as needed
import Footer from "../components/layout/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Ensure Navbar is imported or defined */}

      <body className="flex min-h-screen flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
